### ISSUE TITLE
[BUG] Conflict with fancymenu causing crash (even with notenoughcrashes installed) when rendering the meteor GUI

### ISSUE THREAD

**Issue by BookWyrm114** [JFronny/MeteorAdditions#11]
[latest.log](https://github.com/JFronny/MeteorAdditions/files/8647948/latest.log)

Despite the error messages Vector addon is not causing the issue, I have tested with only meteor and meteoradditions and the crash happens, however with only these two installed notenoughcrashes prevents the game from fully crashing, resulting in this log
[crash-2022-05-08_19.21.26-client.txt](https://github.com/JFronny/MeteorAdditions/files/8647963/crash-2022-05-08_19.21.26-client.txt)
:

**Comment by BookWyrm114** [comment]
hmm, I can't seem to pinpoint the exact mod causing the issue but I found another similar crash issue from another mod: https://github.com/Franckyi/IBE-Editor/issues/47

I'll continue trying to figure out the exact mod causing the issue, but I think this seems to be the thing causing it:

org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)

**Comment by JFronny** [comment]
I think I saw something about rendering outside the render thread, so that issue is not necessarily related.
Anyway, I think I'll close this issue for now, you can re-open it once you find a more narrow combination of mods that cause it.

**Comment by BookWyrm114** [comment]
I narrowed it down to only 6 mods.

![image](https://user-images.githubusercontent.com/79489385/167674607-9d568153-0b66-4830-a816-c0678e4cb689.png)

[Essentials](https://essential.gg/), [Fancymenu](https://www.curseforge.com/minecraft/mc-mods/fancymenu-fabric), and some addons to fancymenu however I suspect core fancymenu is causing the problem.

**Comment by JFronny** [comment]
As I said, just using fancymenu, meteor and meteoradditions doesn't cause a crash and I don't believe the crash only happens with all those

**Comment by BookWyrm114** [comment]
I have tested multiple times with only the above mods installed and the crash happens every time I attempt to open the meteor GUI. This issue also seems to remove the modmenu integration added by MeteorAdditions, as configuration button stops showing up for meteor, yet reappears when the mods are removed.

**Comment by JFronny** [comment]
Using your exact mod list (except for Essentials, as that seems extremely fishy and you stated the issue happened without it), your list of enabled modules and your exact loader version, I can reliably launch an instance that doesn't crash when opening the modules screen.

**Comment by JFronny** [comment]
I can confirm that global layouts apply correctly to the modules screen.
Please create a new instance and figure out the exact set of actions needed to trigger this, as I can't help you like this.
