### ISSUE TITLE
Creative crash

### ISSUE THREAD

**Issue by nmsjayden** [JFronny/MeteorAdditions#33]
When I open my creative inventory it crashes my client, by trail and error I figured out this mod crashes it, it worked originally idk why it doesn't. fix please?

**Comment by JFronny** [comment]
I can't help you without logs and/or a crash report unless the issue happens with just meteor, this and the required dependencies.

**Comment by nmsjayden** [comment]
oh alr i gotchu
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2024-04-15 12:34:26
Description: Rendering screen

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050)
	at meteordevelopment.meteorclient.gui.widgets.containers.WTable.calculateInfo(WTable.java:164)
	at meteordevelopment.meteorclient.gui.widgets.containers.WTable.onCalculateSize(WTable.java:89)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.calculateSize(WWidget.java:45)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:67)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:66)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:66)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:66)
	at meteordevelopment.meteorclient.gui.WidgetScreen$WFullScreenRoot.render(WidgetScreen.java:400)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25394(WidgetScreen.java:269)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050)
	at meteordevelopment.meteorclient.gui.widgets.containers.WTable.calculateInfo(WTable.java:164)
	at meteordevelopment.meteorclient.gui.widgets.containers.WTable.onCalculateSize(WTable.java:89)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.calculateSize(WWidget.java:45)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:67)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:66)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:66)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:66)
	at meteordevelopment.meteorclient.gui.WidgetScreen$WFullScreenRoot.render(WidgetScreen.java:400)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25394(WidgetScreen.java:269)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: de.damcraft.serverseeker.gui.ServerSeekerScreen
	Mouse location: Scaled: (244, 141). Absolute: (731.000000, 424.000000)
	Screen size: Scaled: (456, 256). Absolute: (1366, 768). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Uptime --
Details:
	JVM uptime: 3578.228s
	Wall uptime: 3522.108s
	High-res time: 3503.710s
	Client ticks: 58986 ticks / 2949.300s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, fabric-resource-loader-v0, fabricloader, meteor-client, meteor-crash-addon, serverseeker, tsar-bomba

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 6.6.17-01102-gd3cec3c11146
	Java Version: 22, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 241129200 bytes (229 MiB) / 960495616 bytes (916 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Celeron(R) N4500 @ 1.10GHz
	Identifier: Intel64 Family 6 Model 156 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 1.10
	Number of physical packages: 2
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 1374.88
	Virtual memory used (MB): 1880.76
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Launched Version: 1.20.4
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: virgl (Mesa Intel(R) UHD Graphics (JSL)) GL version 4.3 (Core Profile) Mesa 22.3.6, Mesa/X.org
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 4/4 chunks
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_US
	CPU: 2x Intel(R) Celeron(R) N4500 @ 1.10GHz

-- Meteor Client --

Version: 0.5.6
Dev Build: 2054

[[ Active Modules ]]

[Misc]:
discord-presence

**Comment by nmsjayden** [comment]
I have multiple other logs if you wanna see them

**Comment by JFronny** [comment]
That crash report is probably not the one you wanted to send. It seems to be about a crash in a custom screen provided by "serverseeker", not the inventory.

**Comment by nmsjayden** [comment]
yes I sent the wrong one, I just reinstalled my game and it fixed, thanks though.
