### ISSUE TITLE
disconnect on multiplayer servers when taking/dropping an item out of the saved NBT creative slot

### ISSUE THREAD

**Issue by Modaltryyu** [JFronny/MeteorAdditions#37]
When in creative on a multiplayer server, if trying to take an item out of the saved NBT creative slot, I am disconnected from the server. This also happens when trying to drop the item out of the inventory directly. This issue does not happen on singleplayer worlds, however. The following are the disconnect logs from the debug folder in minecraft.

---- Minecraft Network Protocol Error Report ----
// 0xBADF00D

Time: 2024-12-28 16:07:21
Description: Packet handling error

io.netty.handler.codec.EncoderException: Failed to encode packet 'serverbound/minecraft:set_creative_mode_slot'
	at knot//net.minecraft.class_9136.method_56426(class_9136.java:55)
	at knot//net.minecraft.class_9136.encode(class_9136.java:14)
	at knot//net.minecraft.class_2545.method_10838(class_2545.java:26)
	at knot//net.minecraft.class_2545.encode(class_2545.java:12)
	at knot//io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	at knot//io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	at knot//io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	at knot//io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
	at knot//net.minecraft.class_2535$2.write(class_2535.java:530)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
	at knot//io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
	at knot//io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
	at knot//io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
	at knot//io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at knot//io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
	at knot//net.minecraft.class_2535.method_36942(class_2535.java:350)
	at knot//net.minecraft.class_2535.method_52917(class_2535.java:345)
	at knot//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at knot//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at knot//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at knot//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at knot//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at knot//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: Can't find id for 'Reference{ResourceKey[minecraft:enchantment / minecraft:efficiency]=Enchantment §2 Efficiency}' in map net.minecraft.class_2378$1@5e9be7ff
	at knot//net.minecraft.class_2359.method_56158(class_2359.java:27)
	at knot//net.minecraft.class_9135$16.method_56423(class_9135.java:484)
	at knot//net.minecraft.class_9135$16.encode(class_9135.java:471)
	at knot//net.minecraft.class_9135$13.method_59793(class_9135.java:406)
	at knot//it.unimi.dsi.fastutil.objects.Object2IntMap.lambda$forEach$0(Object2IntMap.java:245)
	at knot//it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapEntrySet.fastForEach(Object2IntOpenHashMap.java:1078)
	at knot//it.unimi.dsi.fastutil.objects.Object2IntMap.forEach(Object2IntMap.java:247)
	at knot//net.minecraft.class_9135$13.method_56418(class_9135.java:405)
	at knot//net.minecraft.class_9135$13.encode(class_9135.java:401)
	at knot//net.minecraft.class_9139$12.encode(class_9139.java:156)
	at knot//net.minecraft.class_9326$1.method_57851(class_9326.java:123)
	at knot//net.minecraft.class_9326$1.method_57850(class_9326.java:109)
	at knot//net.minecraft.class_9326$1.encode(class_9326.java:59)
	at knot//net.minecraft.class_1799$1.method_56100(class_1799.java:156)
	at knot//net.minecraft.class_1799$1.encode(class_1799.java:132)
	at knot//net.minecraft.class_1799$3.method_59695(class_1799.java:200)
	at knot//net.minecraft.class_1799$3.encode(class_1799.java:187)
	at knot//net.minecraft.class_9139$12.encode(class_9139.java:157)
	at knot//net.minecraft.class_9139$9.method_56442(class_9139.java:97)
	at knot//net.minecraft.class_9139$9.encode(class_9139.java:87)
	at knot//net.minecraft.class_9136.method_56426(class_9136.java:53)
	... 26 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Netty Client IO #6
Stacktrace:
	at knot//net.minecraft.class_2547.method_55622(class_2547.java:33)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: Spigot
Stacktrace:
	at knot//net.minecraft.class_2547.method_55622(class_2547.java:33)
	at knot//net.minecraft.class_2600.method_59803(class_2600.java:62)
	at knot//net.minecraft.class_8673.method_60882(class_8673.java:136)
	at knot//net.minecraft.class_8673.method_60881(class_8673.java:127)
	at knot//net.minecraft.class_2535.exceptionCaught(class_2535.java:161)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at knot//io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at knot//io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at knot//io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at knot//io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:69)
	at knot//io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:65)
	at knot//io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at knot//io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at knot//io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at knot//io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185)
	at knot//io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at knot//io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at knot//net.minecraft.class_2535.method_36942(class_2535.java:364)
	at knot//net.minecraft.class_2535.method_52917(class_2535.java:345)
	at knot//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at knot//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at knot//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at knot//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at knot//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at knot//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 752404920 bytes (717 MiB) / 2046820352 bytes (1952 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.69
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.5186
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 30936.49
	Virtual memory used (MiB): 23821.57
	Swap memory total (MiB): 14848.00
	Swap memory used (MiB): 1034.43
	Space in storage for jna.tmpdir (MiB): available: 87418.16, total: 975461.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 87418.16, total: 975461.00
	Space in storage for io.netty.native.workdir (MiB): available: 87418.16, total: 975461.00
	Space in storage for java.io.tmpdir (MiB): available: 87418.16, total: 975461.00
	Space in storage for workdir (MiB): available: 87418.16, total: 975461.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.6.6
		ambientsounds: AmbientSounds 6.1.3
		anticreativedrift: Anti Creative Drift 1.0
		antique_atlas: Antique Atlas 2.10.1+1.21
		appleskin: AppleSkin 3.0.6+mc1.21
		architectury: Architectury 13.0.8
		authme: Auth Me 8.0.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
		badpackets: Bad Packets 0.8.1
		balm-fabric: Balm 21.0.20
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		baritone-meteor: Baritone 1.21.1-SNAPSHOT
			dev_babbaj_nether-pathfinder: nether-pathfinder 1.4.1
		betteradvancements: Better Advancements 0.4.3.21
		betteranimationscollection: Better Animations Collection 21.1.0
		betterf1: BetterF1 1.0
		betterf3: BetterF3 11.0.2
		bettermounthud: Better Mount HUD 1.2.4
		book-formatting: §9Book §a§oFormatting 1.0.0
		bookshelf: Bookshelf 21.1.13
		centered-crosshair: Centered Crosshair 1.0.8
		chatanimation: ChatAnimation 1.0.6
		chatcalc: ChatCalc 4.1.8
		chatnotify: ChatNotify 2.2.0+1.21
		chatpatches: Chat Patches 211.6.9
		chattools: Chat Tools 2.3.6.1
			com_sshtools_two-slices: two-slices 0.9.4
		chesttracker: Chest Tracker 2.6.2+1.21.1
			whereisit: Where Is It 2.6.3+1.21.1
				jackfredlib: JackFredLib 0.10.2+1.21.1
					jackfredlib-base: JackFredLib: Base 1.4.1+1.21.1
					jackfredlib-colour: JackFredLib: Colour 1.1.0+1.21.1
					jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.1+1.21.1
					jackfredlib-gps: JackFredLib: GPS 1.0.7+1.21.1
					jackfredlib-lying: JackFredLib: Lying 0.5.5+1.21.1
					jackfredlib-toasts: JackFredLib: Toasts 1.1.1+1.21.1
		cicada: CICADA 0.9.1+1.21-1.21.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		commanddumper: CommandDumper 1.0
		continuity: Continuity 3.0.0+1.21
		controlling: Controlling 19.0.3
		coroutil: CoroUtil 1.21.0-1.3.7
		craftify: Craftify 1.16.0
		crash-command: Crash Command 1.0.0
		creativecore: CreativeCore 2.12.22
			net_neoforged_bus: bus 7.2.0
		customizableelytra: Customizable Elytra 2.2.7+1.21
		dark-loading-screen: Dark Loading Screen 1.6.14
		deathlog: DeathLog 0.4.1+1.21
		debugify: Debugify 1.21.1+1.0
		do_a_barrel_roll: Do a Barrel Roll 3.7.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.2-beta.4
		dynamiccrosshair: Dynamic Crosshair 9.3
			dynamiccrosshair-api: DynamicCrosshair API 1.1
			libbamboo: LibBamboo 2.2
		eatinganimationid: Eating Animation 1.21+1.9.72
		elchantment-level-fix: Elchantment Level Fix 1.1.0
		elytra_physics: Elytra Physics 2.1_mc1.19.3+
		elytrahud: ElytraHud (MFS 2020) 1.1.0
		elytratime: Elytra Time 2.1.0
		emojitype: Emoji Type 2.3.0-1.21.3
		enchdesc: EnchantmentDescriptions 21.1.5
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		essential: Essential 1.3.5.5
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		essential-dependencies: Essential Dependencies 0
			elementa: Elementa 670
			universalcraft: UniversalCraft 365
			vigilance: Vigilance 306
		evilcreativefly: Creative Fly 1.4.3-1.21-fabric
		fabric-api: Fabric API 0.107.0+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.69+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.17+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+7fd4837519
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+e49211d819
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.22+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+0f6c53cd19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.13.0+kotlin.2.1.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.1.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.26.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		fasttrading: Fast Trading 0.2.0+1.21
			midnightlib: MidnightLib 1.6.3
		ferritecore: FerriteCore 7.0.2-hotfix
		flashback: Flashback 0.15.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
		forgeconfigapiport: Forge Config API Port 21.1.1
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		fzmm: FZMM 0.2.16
			placeholder-api: Placeholder API 2.4.1+1.21
		geckolib: GeckoLib 4 4.7
		gurkensgadgetry: Gurken's Gadgetry 1.4.0
		hidden_items_tabs: Creative Inv Extension 1.1.3-1.21.1
		highlighter: Highlighter 1.1.11
		higtools: HIGTools 2.9.1
		iceberg: Iceberg 1.2.7
		ikea: IKEA Addon 0.2.2
		immersiveui: ImmersiveUI 0.2.2
		infinite-music: Infinite Music 0.4.4
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		jeed: Just Enough Effects Descriptions 1.21-2.2.9
		jei: Just Enough Items 19.21.0.247
		jeresources: Just Enough Resources 1.6.0.11
		legendarytooltips: Legendary Tooltips 1.4.11
		lyra-addon: Lyra Addon 0.8.0
		malilib: MaLiLib 0.21.5
		meteor-additions: MeteorAdditions 1.2.0
			google-chat: GoogleChat 0.9.0
			libjf-base: LibJF Base 3.17.3
			libjf-config-core-v2: LibJF Config 3.17.3
			libjf-translate-v1: LibJF Translate 3.17.3
		meteor-client: Meteor Client 0.5.8-2192
		meteor-villager-roller: Meteor Villager Roller 1.4.8+mc1.21.1-rev.494c4b6-dirty
		meteorist: Meteorist 1.10
		meteorplus: Meteor+ 1.21.1_1.0.9.0
		minecraft: Minecraft 1.21.1
		minepedia: Minepedia 1.2
		minihud: MiniHUD 0.32.54
		modernfix: ModernFix 5.19.5+mc1.21.1
		modmenu: Mod Menu 11.0.3
		monsters_in_the_closet: Monsters in the Closet 1.0.3+1.21
		musicnotification: Music Notification 2.1.0
		nbt_ac: NBT Autocomplete 1.3.10
		nbt_copy: NBT Copy 1.0.3
		nochatreports: No Chat Reports 1.21.1-v2.9.0
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		norefreshscroll: NoRefreshScroll 1.0.10
		notenoughcrashes: Not Enough Crashes 4.4.8+1.21
		notifications-addon: Notifications Addon 3.1.0
		numbyhack: Numby Hack 2.3
		octolib: OctoLib 0.5
			org_yaml_snakeyaml: snakeyaml 2.2
		openboatutils: OpenBoatUtils 0.4.3_1.21
		org_jetbrains_annotations: annotations 23.0.0
		owo: oωo 0.12.13+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		peek: Peek 1.21.1-1.3.6
		ping-wheel: Ping Wheel 1.10.0
		plasmovoice: Plasmo Voice 2.1.1
		prickle: PrickleMC 21.1.6
		prism: root project 'Prism' 1.0.9
		puzzleslib: Puzzles Lib 21.1.24
		pv-addon-replaymod: pv-addon-replaymod 2.1.1
		quick_commands: QuickCommands 1.2-1.21.1
		rebind_narrator: Rebind Narrator 2.0.3
		reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.4+mc1.21.1
		replaymod: Replay Mod 1.21-2.6.20
		rrls: Remove Reloading Screen 5.0.8+mc1.21.1-fabric
		searchables: Searchables 1.0.2
		servercountryflags: Server Country Flags 1.10.4
		serverpingerfixer: Server Pinger Fixer 1.0.5
		shouldersurfing: Shoulder Surfing Reloaded 4.6.1
		showoperatortab: Show Operator Tab 1.0.0
		shulkerboxtooltip: Shulker Box Tooltip 5.1.2+1.21.1
		shutupdeadentities: ShutUpDeadEntities 1.1
		simple-item-editor: Simple Item Editor 0.1.2
		sodium: Sodium 0.6.0-beta.4+mc1.21.1
		sodium-extra: Sodium Extra 0.6.0-beta.3+mc1.21.1
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		soundboard-svc: Voice Chat Soundboard 0.7.0
			kowoui: Kotlin OwO UI 0.3.0
			soundboard-core: Soundboard Core 0.7.0
				com_squareup_okhttp3_okhttp: okhttp 4.12.0
				com_squareup_okio_okio-jvm: okio-jvm 3.9.1
		spu: Server Pack Unlocker 1.8
		status-effect-bars: Status Effect Bars 1.0.6
		statuseffecttimer: Status Effect Timer 1.2.0+1.21
		stendhal: Stendhal 1.4.1-1.21
			libgui: LibGui 11.0.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		streak-addon: TrouserStreak 1.2.7
		surveyor: Surveyor Map Framework 0.6.25+1.21
			folk_sisby_kaleido-config: kaleido-config 0.3.1+1.3.2
		symbol-chat: Symbol Chat 1.21.1-1.2.8
		talkbubbles: Talk Bubbles 1.0.8
		texturized-particles: Texturized Particles 1.0.1+1.21
		threadtweak: ThreadTweak 0.1.5+mc1.21.1
		tipsmod: Tips 21.1.2
		titlefixer: Title Fixer 1.0+1.21
		tooltipfix: ToolTip Fix 1.1.1-1.20
		totemcounter: TotemCounter 1.6.1+mc1.21
		trim-command: Trim command 1.0.0
		ukulib: ukulib 1.4.1+1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		usageticker: Usage Ticker 1.0.1-1.21
		visuality: Visuality 0.7.7+1.21
		voicechat: Simple Voice Chat 1.21.1-2.5.25
		waveycapes: WaveyCapes 1.4.13
		weaponmaster_ydm: YDM's Weapon Master 4.2.3
		worldedit: WorldEdit 7.3.8+6939-7d32b45
		wthit: wthit 12.4.5
		xaerominimap: Xaero's Minimap 24.7.1
		xaeros-map-chest-tracker-integration: Xaero's Map Chest Tracker Integration 3.0.2
			conditional-mixin: conditional mixin 0.4.0
		xaeroworldmap: Xaero's World Map 1.39.2
		xaerozoomout: XaeroZoomout 2.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zume: Zume 1.1.4
	Loaded Shaderpack: (off)
	Suspected Mods: Minecraft (minecraft)a

-- Meteor Client --

Version: 0.5.8
Dev Build: 2192

[[ Active Modules ]]

[Combat]:
hitboxes

[Render]:
better-tab
block-selection
blur
fullbright
tracers
trajectories

I hope this issue can be resolved soon and I thank you for taking this time to review my issue.

**Comment by JFronny** [comment]
Should now be fixed. If it is not, please reopen the issue.

(Also: GitHub markdown provides a "details" tag (accessible through an icon at the top right of your WYSIWYG editor) which you can use to make your next report much more readable)
